version: '2'

services:
  web:
    image: steverichards/drupal-apache-php56
    ports:
     - "8080:80"
    volumes:
      - ./conf/php:/usr/local/etc/php/conf.d
      - ../docroot:/var/www/html
    links:
     - mysql
     - memcached

  # MySQL Server
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - "3306"

  # Memcached server
  memcached:
    image: memcached
    ports:
      - "11211"